### ISSUE TITLE
aioify don't wrap imported modules and objects from other modules inside the requested module (for example, when wrapping os, os.path is not wrapped)

### ISSUE THREAD

**Issue by NightMachinary** [yifeikong/aioify#17]
The old API “await aios.path.exists('/')” no longer works. Why? Is there any way to smoothly upgrade? If not, what is the latest version of the old API installable by pip?

**Comment by rominf** [comment]
Hi, @NightMachinary.

Sorry for breaking the API. The reason is that previous implementation recursed to the full depth of the object members, including objects (modules, for example) from other modules. It was bad because:
1. It's not efficient (probably we need to wrap thousands of objects).
2. It's not obvious (I call `aioify` for the particular module but it wraps all related modules).
3. It's not convenient in most cases (imaging `str` in the wrapped module; it will be wrapped too, that means that you will have to call `await aiomodule.s.split()`; most probably you don't want that).

Now we are wrapping the objects from the same module. This has its own downsides, sure.

Let's return to your example: `os.path` is a module from the different file (`posixpath.py` for POSIX), so it's not wrapped. I don't know an elegant solution that would wrap `os.path`, but would not wrap `os.abc` and `os.curdir` for example.

You can suggest the solution, we will think about it. The best thing I can imagine (without hardcoding) would be something like:
```python
from aioify import aioify
from os import path
import genericpath

aiopath = aioify(path, wrap_filenames=[genericpath.__file__])
```
Ugly, but explicit.

If you are talking just about `os.path`, the easiest thing to do IMHO would convert your code to use `aiopathlib = aioify(pathlib)`, because it just works. I suggest you read this: https://treyhunner.com/2018/12/why-you-should-be-using-pathlib/

**Comment by NightMachinary** [comment]
Thanks! Since the previous API worked just fine for my limited purposes, I
just downgraded to 0.1.3 and everything’s good. :D
This “inefficient” behavior is quite to my liking; The computer does extra
work, I the programmer don’t, and things work just fine. (Though I do
appreciate the new API.)
Feel free to close this issue.

**Comment by rominf** [comment]
@NightMachinary, OK. Thank you for your report! I've got some other ideas about how to do it explicitly but more elegantly. I'll ping you back just in case if/when I implement that.

I will keep this issue open because of 0.1.3 has quite a few drawbacks comparing to the latest version and downgrading is not a solution for everyone.

**Comment by rominf** [comment]
Hi @NightMachinary. If it's still valuable for you, I've made a quite simple fix for this (in the latest version on PyPI):
```python
In [1]: from aioify import aioify
   ...: import os
   ...: aios = aioify(os, name="aios")
   ...: await aios.path.exists("/")
Out[1]: True
```

**Comment by NightMachinary** [comment]
Thanks! I guess I can upgrade after all these months :D

**Comment by rominf** [comment]
Caution: this library is based on my `module-wrapper,` which involves strong black magic; both libraries are still alpha quality (and probably will always be, because of the dynamic nature of Python); use it only with enough testing.
